Update ci-cd.yaml

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -48,6 +48,10 @@ jobs:
 
       - name: Deploy to Kubernetes
         run: |
+           echo "Printing directory tree:"
+           ls -la
+           echo "Checking contents of k8s directory:"
+           ls -la k8s || echo "⚠️ k8s directory not found"
            mkdir -p k8s
            sed "s|IMAGE_TAG|${{ env.VERSION }}|g" k8s/deployment-template.yaml > k8s/deployment.yaml
            kubectl apply -f k8s/deployment.yaml
